// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVhdwtdmRJMzDwsdfqjiIBEhKNBRzyKH8',
    appId: '1:397746096516:web:121316db69a3190ceeb5d1',
    messagingSenderId: '397746096516',
    projectId: 'music-dc298',
    authDomain: 'music-dc298.firebaseapp.com',
    storageBucket: 'music-dc298.firebasestorage.app',
    measurementId: 'G-LTZY7HNTC7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6hjYKxftCkxc_-yRsTy-oGGzwsssIO4M',
    appId: '1:397746096516:android:bac68fac2c5f2097eeb5d1',
    messagingSenderId: '397746096516',
    projectId: 'music-dc298',
    storageBucket: 'music-dc298.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6dyvdyskJtl2O4QIJsx23TnxFBmZ2IAY',
    appId: '1:397746096516:ios:118bcca7fc973145eeb5d1',
    messagingSenderId: '397746096516',
    projectId: 'music-dc298',
    storageBucket: 'music-dc298.firebasestorage.app',
    iosBundleId: 'com.example.listenMusic',
  );
}
